### ISSUE TITLE
[Deprecation Message] wasm-bindgen glue code: using deprecated parameters for the initialization function

### ISSUE THREAD

**Issue by hansSchall** [cunarist/tokio-with-wasm#13]
The worker init code calls the `__wbg_init` function with two arguments which is depecated and prints a warning to console. Instead of the two args a configuration object should be passed.

```
using deprecated parameters for the initialization function; pass a single object instead
```

**Comment by temeddix** [comment]
Thanks for the report, I'll fix this as soon as possible :) Meanwhile we are also open to PRs if you need faster support

**Comment by hansSchall** [comment]
Its just a warning ;-)

**Comment by temeddix** [comment]
I'm actually not sure where this message is coming from yet. Would it be the issue from outdated version of `wasm-bindgen`? Still investigating..

**Comment by hansSchall** [comment]
It looks like wasm-bindgen is migrating from a parameter function to a config object. Unfortunately there are no official docs on this config object, only the code that is generated. Currently tokio-with-wasm passes an array to the worker which is spread to the params. I could fix this tomorrow...
