### ISSUE TITLE
Memory error with WorkerPool `spawn_blocking`

### ISSUE THREAD

**Issue by Slixe** [cunarist/tokio-with-wasm#19]
Hey, it's me again.

Here is the log I'm getting:
```
Error from `flush_queued_tasks` in `tokio-with-wasm`: JsValue(DataCloneError: Failed to execute 'postMessage' on 'Worker': #<Memory> could not be cloned.
DataCloneError: Failed to execute 'postMessage' on 'Worker': #<Memory> could not be cloned.
```

with the following minimal example (which is from your `spawn_blocking` function doc:
https://github.com/Slixe/xelis-captcha

Building with no-module or web target don't change anything.

Am I missing anything ? I've followed https://github.com/cunarist/tokio-with-wasm?tab=readme-ov-file#building-and-deploying with no success.

**Comment by temeddix** [comment]
I was able to make your example work by providing proper configs to the `wasm-pack` command.

- https://github.com/temeddix/xelis-captcha

The `compile.py` file that I wrote be of help.

**Comment by Slixe** [comment]
Thanks a lot, maybe it would be worth adding it in the README too ?

I thought everything was fine, but the error was on me, sorry!

**Comment by Slixe** [comment]
@temeddix sorry to ping you, should I do a PR to add the missing part in the README.md in order to prevent any issues like mine ?

**Comment by temeddix** [comment]
Yeah, adding relevant info to the readme file would be a big help. I'm personally busy right now, so any kind of PR for that would be greatly appreciated :)

**Comment by b-zee** [comment]
I just came across this issue, but am running `wasm-pack test`. Testing doesn't support arguments like `--target=web`, so not sure if it's possible at all.

Am I understanding correctly that a nightly compiler is needed in combination with passing `-Z build-std=std,panic_abort`?

**Comment by Slixe** [comment]
@b-zee maybe you're more interested in #3 ?
